#: import Menu NeirianaRosa.uix.object.screen.menu.Menu
#: import Menu NeirianaRosa.uix.object.screen.story.Story
#: import Menu NeirianaRosa.uix.object.screen.generate_story.GenerateStory
#: import Menu NeirianaRosa.uix.object.screen.tabua.Tabua
<Manager>:
    Menu:
        id:menu
        name:'Menu'

    Story:
        id:story
        name:'Story'

    GenerateStory:
        id:generate_story
        name:'Generate Story'

    Tabua:
        id:tabua
        name:'Tabua'
